spring:
  datasource:
    url: jdbc:mysql://192.168.10.131:3306/icbc?&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  application:
    name: yyicbc-zuul-gateway
  devtools:
    restart:
      enabled: false

#http://myzuul.com:9527/yyicbcservice-pro1/dept/list
#踩坑：访问路径大小写敏感
server:
  port: 9001

eureka:
  instance:
    instance-id: gateway-9001
    prefer-ip-address: true
  client:
    service-url:
      # 单机版配置defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置与eureka server 交互的地址查询服务和注册服务都需要依赖的地址
      #集群配置
      defaultZone: http://eureka8001.com:8001/eureka/,http://eureka8002.com:8002/eureka/,http://eureka8003.com:8003/eureka/


#http://myzuul.com:9527/yymacau/yyicbc/dept/list
zuul:
  routes:
    yyicbc.serviceId: yyicbcservice-pro1
    yyicbc.path: /yyicbc/**
  #多个用"*" ignored-services: "*"
  ignored-services: yyicbcservice-pro1
#  #公共前缀
  prefix: /yymacau

