server:
  port: 10000


spring:
  application:
    name: spring-boot-admin-server
  profiles: test
  security:
    user:
      name: yyicbc
      password: 123456
  boot:
    admin:
      ui:
        title: Yyicbc Monitor Center
        brand: "<img src=\"assets/img/icon-spring-boot-admin.svg\"><span>Yyicbc Monitor Centre</span>"

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      user:
        name: yyicbc
        password: 123456
  client:
    registry-fetch-interval-seconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always